.PHONY: all
all: server/middfs-server client/middfs-client

server/middfs-server: server/Makefile
	cd server && $(MAKE) middfs-server

client/middfs-client: client/Makefile
	cd client && $(MAKE) middfs-client
